# spring:
#   datasource:
#     url: jdbc:h2:mem:tarefasdb
#     driverClassName: org.h2.Driver
#     username: sa
#     password:
#   h2:
#     console:
#       enabled: true
#       path: /h2-console
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SistemaDeTarefas_db?useSSL=false&serverTimezone=UTC
    username: root
    password: Julion235506!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
